name: sma_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.16
  - pip=25.0
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - xarray=2024.11.0
  - matplotlib=3.10.0
  - numpy=1.26.4
  - scipy=1.15.1
  - ipython=8.30.0
  - jupyter=1.1.1
  - tqdm=4.66.2
  - pillow=11.1.0
  - opencv=4.10.0
  - pip:
    - ipykernel==6.29.5
    - python-dotenv==1.0.1
    - destinelab==1.1
    - netCDF4==1.7.2
    - cartopy==0.24.1
